language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
before_script:
  - echo "deb http://archive.ubuntu.com/ubuntu xenial universe" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install libopenblas-dev
  - sudo apt-get install libdlib-dev  

  - export CXX=/usr/bin/g++-7
  - export CC=/usr/bin/gcc-7

script: 
  - cmake .
  - cmake --build .
  - cmake --build . --target package  
deploy: 
  - provider: script
    skip_cleanup: true
    script:       
     - curl -T realty-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -upk-otus:$BINTRAY_API_KEY "https://api.bintray.com/content/pk-otus/OTUS/realty/$TRAVIS_BUILD_NUMBER/realty.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1" 
  
